AnimDispa/Models/Animaux.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AnimDispa.Models
{
    [Table("Animaux")]
    public class Animaux {
        
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Poids { get; set; }
        public string Couleur { get; set; }
        public string Tatouage { get; set; }
        public string Puce { get; set; }
        public string PhotoPrincipale { get; set; }
        public string Rue { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }




        public int IdDepartement { get; set; }
        [ForeignKey(nameof(IdDepartement))]
        public virtual Departements Departement { get; set; }
        
        public int IdRaces { get; set; }
        [ForeignKey(nameof(IdRaces))]
        public virtual Races Race { get; set; }

        public int IdCompte { get; set; }
        [ForeignKey(nameof(IdCompte))]
        public virtual Comptes Compte { get; set; }

        public int idStatut { get; set; }
        [ForeignKey(nameof(idStatut))]
        public virtual StatutsAnimaux StatutAnimal { get; set; }
        
        public virtual ICollection<Messages> LesMessages { get; set; }


        public Animaux()
        {

        }

        public Animaux(int id, string nom, string poids, string couleur, string tatouage, string puce, string photoPrincipale)
        {
            Id = id;
            Nom = nom;
            Poids = poids;
            Couleur = couleur;
            Tatouage = tatouage;
            Puce = puce;
            PhotoPrincipale = photoPrincipale;
        }
    }
}

AnimDispa/Controllers/AjaxController.cs
using AnimDispa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AnimDispa.Controllers
{
    public class AjaxController : Controller
    {
        private AnimDispaContext db = new AnimDispaContext();
        public JsonResult MarkerAdd(string lat, string lgt, int? idAnim)
        {
            Signalements Sign = new Signalements();
            Sign.Date = DateTime.Now;
            Sign.Latitude = lat;
            Sign.Longitude = lgt;
            Sign.IdAnimaux = (int)idAnim;
            Sign.Animaux = db.Animaux.Find(idAnim);
            db.Signalements.Add(Sign);
            db.SaveChanges();
            var Sort = Json(Sign);
            return Json(Sort,JsonRequestBehavior.AllowGet);
        }
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }

        // GET: Ajax/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Ajax/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ajax/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        
        // GET: Ajax/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Ajax/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ajax/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Ajax/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AnimDispa/Controllers/AnimauxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using AnimDispa.Models;
using System.Web.Mvc;
using System.Web.Helpers;
using System.IO;

namespace AnimDispa.Controllers
{
    public class AnimauxController : Controller
    {

        private AnimDispaContext db = new AnimDispaContext();

        // GET: Animal
        public ActionResult Index(int id)
        {

            var model = new ViewModelAnimaux()
            {
                animal = db.Animaux.Find(id),
                lesMessages = db.Messages.Where(x => x.Animal.Id == id).ToList(),
                conf = db.Config.Find(1),
                ListeMarker = db.Signalements.Where(x => x.IdAnimaux == id).ToList()
            };

            return View(model);
        }


        public ActionResult Add()
        {


            var model = new ViewModelAnimauxEdit()
            {
                lesRaces = db.Races.ToList(),
                lesTypes = db.Types.ToList(),
                lesDepartements = db.Departements.ToList()
            };



            return View(model);
        }

        public ActionResult AddConfirm(string nom, string poids, string couleur, string tatouage, string puce, int race, int departement, string rue, string cp, string ville, HttpPostedFileBase upload)
        {

            Animaux animal = new Animaux();
            animal.Nom = nom;
            animal.Poids = poids;
            animal.Couleur = couleur;
            animal.Tatouage = tatouage;
            animal.Puce = puce;
            animal.Race = db.Races.Find(race);
            animal.PhotoPrincipale = upload.FileName;
            animal.Departement = db.Departements.Find(departement);
            animal.Rue = rue;
            animal.CodePostal = cp;
            animal.Ville = ville;
            animal.StatutAnimal = db.StatutAnimal.Find(1);

            if (Session["idConnecte"] != null)
            {
                animal.Compte = db.Comptes.Find(Session["idConnecte"]);
            }
            else {
                animal.Compte = db.Comptes.Find(7);
            }

            db.Animaux.Add(animal);
            db.SaveChanges();


            if (upload != null && upload.ContentLength > 0)
            {

                string RootFolder = @Server.MapPath("~/content/img");
                string path = Path.Combine(RootFolder, upload.FileName);
                upload.SaveAs(path);
            }


            return RedirectToAction("Index", "Animaux", new { id = animal.Id });
        }



        public ActionResult Edit(int id)
        {

            var model = new ViewModelAnimauxEdit()
            {
                lesRaces = db.Races.ToList(),
                lesTypes = db.Types.ToList(),
                lesDepartements = db.Departements.ToList(),
                animal = db.Animaux.Find(id),
                LesStatutsAnimaux = db.StatutAnimal.ToList()
            };

            return View(model);
        }

        public ActionResult EditConfirm(int id, int statutAnimal, string nom, string poids, string couleur, string tatouage, string puce, int race, int departement, string rue, string cp, string ville) {

            Animaux animal = db.Animaux.Find(id);
            animal.Nom = nom;
            animal.Poids = poids;
            animal.Couleur = couleur;
            animal.Tatouage = tatouage;
            animal.Puce = puce;
            animal.Race = db.Races.Find(race);
            animal.Departement = db.Departements.Find(departement);
            animal.Rue = rue;
            animal.CodePostal = cp;
            animal.Ville = ville;
            animal.StatutAnimal = db.StatutAnimal.Find(statutAnimal);


            if (Session["idConnecte"] != null) {
                animal.Compte = db.Comptes.Find(Session["idConnecte"]);
            }
            else {
                animal.Compte = db.Comptes.Find(7);
            }

            db.SaveChanges();

            return RedirectToAction("Index", "Animaux", new { id = animal.Id });
        }
    }
}

AnimDispa/Views/Animaux/Add.cshtml
@model AnimDispa.Models.ViewModelAnimauxEdit

@{
    ViewBag.Title = "Add";
}

<div class="jumbotron">
    <h1>AnimDispa</h1>
    <p class="lead">Site pour déclarer la perte de son animal de compagnie</p>
</div>

<h2>Signaler un animal perdu</h2>
<hr />

<div class="form-horizontal">

    <form action="AddConfirm" method="POST" enctype="multipart/form-data">

        <!-- NOM -->
        <div class="form-group">
            <label class="control-label col-md-2" for="nom">Nom</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="nom" name="nom" type="text" value="">
            </div>
        </div>



        <!-- POIDS -->
        <div class="form-group">
            <label class="control-label col-md-2" for="poids">Poids (Kg)</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="poids" name="poids" type="number">
            </div>
        </div>



        <!-- COULEUR -->
        <div class="form-group">
            <label class="control-label col-md-2" for="couleur">Couleur</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="couleur" name="couleur" type="text">
            </div>
        </div>



        <!-- TATOUAGE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="tatouage">Tatouage</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="tatouage" name="tatouage" type="text">
            </div>
        </div>



        <!-- PUCE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="puce">Puce</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="puce" name="puce" type="text">
            </div>
        </div>



        <!-- TYPE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="type">Type</label>
            <div class="col-md-10">

                <select id="type" class="form-control text-box single-line" name="type" required onchange="jsRaces();">
                    <option></option>
                    @foreach (var item in Model.lesTypes)
                    {
                        <option value="@Html.DisplayFor(modelItem => item.Id)">@Html.DisplayFor(modelItem => item.Libelle)</option>

                    }
                </select>
            </div>
        </div>



        <!-- RACE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="race">Race</label>
            <div class="col-md-10">

                <select id="race" class="form-control text-box single-line" name="race" required>
                    <option></option>
                    @foreach (var item in Model.lesRaces)
                    {
                        <option hidden class="@Html.DisplayFor(modelItem => item.Type.Id)" value="@Html.DisplayFor(modelItem => item.Id)">@Html.DisplayFor(modelItem => item.Libelle)</option>

                    }
                </select>
            </div>
        </div>



        <!-- IMAGE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="img">Image Principale</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line btn-primary" required id="img" name="upload" type="file">
            </div>
        </div>



        <hr />



        <!-- DEPARTEMENT -->
        <div class="form-group">
            <label class="control-label col-md-2" for="departement">Departement</label>
            <div class="col-md-10">

                <select id="departement" class="form-control text-box single-line" name="departement" required>
                    <option></option>
                    @foreach (var item in Model.lesDepartements)
                    {
                        <option value="@Html.DisplayFor(modelItem => item.Id)">@Html.DisplayFor(modelItem => item.numero) - @Html.DisplayFor(modelItem => item.Libelle)</option>

                    }
                </select>
            </div>
        </div>



        <!-- RUE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="rue">Rue</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="rue" name="rue" type="text">
            </div>
        </div>



        <!-- CODE POSTAL -->
        <div class="form-group">
            <label class="control-label col-md-2" for="cp">Code Postal</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="cp" name="cp" type="text">
            </div>
        </div>



        <!-- Ville -->
        <div class="form-group">
            <label class="control-label col-md-2" for="ville">Ville</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="ville" name="ville" type="text">
            </div>
        </div>



        <!-- SUBMIT -->
        <div class="form-group">
            <label class="control-label col-md-2" for="Nom"></label>
            <div class="col-md-10">
                <input class="form-control text-box single-line btn-primary" type="submit">
            </div>
        </div>

    </form>

</div>

<script type="text/javascript">

    function jsRaces() {
        var race = document.getElementById("type").selectedIndex;
        document.getElementById("race").selectedIndex = null;

        $("#race option").each(function () {
            if (this.className == race) {
                this.hidden = false;
            } else {
                this.hidden = true;
            }

        });

    }

</script>

AnimDispa/Views/Animaux/Edit.cshtml
@model AnimDispa.Models.ViewModelAnimauxEdit

@{
    ViewBag.Title = "Add";
}

<style>
    .statutFont {
        font-weight: bold;
        color: #FFF;
    }
</style>

<div class="jumbotron">
    <h1>AnimDispa</h1>
    <p class="lead">Site pour déclarer la perte de son animal de compagnie</p>
</div>

<h2>Signaler un animal perdu</h2>
<hr />

<div class="form-horizontal">

    <form action="/Animaux/EditConfirm" method="POST" enctype="multipart/form-data">

        <input type="hidden" name="id" value="@Html.DisplayFor(x => x.animal.Id)" />

        <!-- NOM -->
        <div class="form-group">
            <label class="control-label col-md-2" for="nom">Nom</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="nom" name="nom" type="text" value="@Html.DisplayFor(x => x.animal.Nom)">
            </div>
        </div>



        <!-- POIDS -->
        <div class="form-group">
            <label class="control-label col-md-2" for="poids">Poids (Kg)</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="poids" name="poids" type="number" value="@Html.DisplayFor(x => x.animal.Poids)">
            </div>
        </div>



        <!-- COULEUR -->
        <div class="form-group">
            <label class="control-label col-md-2" for="couleur">Couleur</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="couleur" name="couleur" type="text" value="@Html.DisplayFor(x => x.animal.Couleur)">
            </div>
        </div>



        <!-- TATOUAGE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="tatouage">Tatouage</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="tatouage" name="tatouage" type="text" value="@Html.DisplayFor(x => x.animal.Tatouage)">
            </div>
        </div>



        <!-- PUCE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="puce">Puce</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="puce" name="puce" type="text" value="@Html.DisplayFor(x => x.animal.Puce)">
            </div>
        </div>



        <!-- TYPE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="type">Type</label>
            <div class="col-md-10">

                <select id="type" class="form-control text-box single-line" name="type" required onchange="jsRaces();">
                    <option></option>
                    @foreach (var item in Model.lesTypes)
                    {
                        <option     value="@Html.DisplayFor(modelItem => item.Id)"
                                    @if (item.Id == Model.animal.Race.Type.Id) {
                                        @:selected
	                                }
                        >
                            @Html.DisplayFor(modelItem => item.Libelle)
                        </option>

                    }
                </select>
            </div>
        </div>



        <!-- RACE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="race">Race</label>
            <div class="col-md-10">

                <select id="race" class="form-control text-box single-line" name="race" required>
                    <option></option>
                    @foreach (var item in Model.lesRaces) {
                        <option     class="@Html.DisplayFor(modelItem => item.Type.Id)"
                                    value="@Html.DisplayFor(modelItem => item.Id)"
                                    @if (item.Id == Model.animal.Race.Id) {
                                        @:selected
	                                }
                                    @if (item.Type != Model.animal.Race.Type) {
                                        @:hidden
	                                }
                        >
                            @Html.DisplayFor(modelItem => item.Libelle)
                        </option>

                    }
                </select>
            </div>
        </div>



        <!-- STATUT COMPTE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="type">Statut</label>
            <div class="col-md-10">

                <select id="statutAnimal" class="form-control text-box single-line statutFont" name="statutAnimal" required style="background-color: @Html.DisplayFor(x => x.animal.StatutAnimal.Couleur)" onchange="changeStatut()">

                    @foreach (var item in Model.LesStatutsAnimaux) {

                        <option value="@Html.DisplayFor(modelItem => item.Id)"
                                @if (item.Id == Model.animal.StatutAnimal.Id) { @: selected
                                	                                }>
                            @Html.DisplayFor(modelItem => item.Libelle)
                        </option>
                    }
                </select>
            </div>
        </div>
        
        
        
        <hr />



        <!-- DEPARTEMENT -->
        <div class="form-group">
            <label class="control-label col-md-2" for="departement">Departement</label>
            <div class="col-md-10">

                <select id="departement" class="form-control text-box single-line" name="departement" required>
                    <option></option>
                    @foreach (var item in Model.lesDepartements)
                    {
                        <option     value="@Html.DisplayFor(modelItem => item.Id)"
                                    @if (item.Id == Model.animal.Departement.Id) {
                                        @:selected
	                                }
                        >
                            @Html.DisplayFor(modelItem => item.numero) - @Html.DisplayFor(modelItem => item.Libelle)
                        </option>

                    }
                </select>
            </div>
        </div>



        <!-- RUE -->
        <div class="form-group">
            <label class="control-label col-md-2" for="rue">Rue</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="rue" name="rue" type="text" value="@Html.DisplayFor(x => x.animal.Rue)">
            </div>
        </div>



        <!-- CODE POSTAL -->
        <div class="form-group">
            <label class="control-label col-md-2" for="cp">Code Postal</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="cp" name="cp" type="text" value="@Html.DisplayFor(x => x.animal.CodePostal)">
            </div>
        </div>



        <!-- Ville -->
        <div class="form-group">
            <label class="control-label col-md-2" for="ville">Ville</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="ville" name="ville" type="text" value="@Html.DisplayFor(x => x.animal.Ville)">
            </div>
        </div>



        <!-- SUBMIT -->
        <div class="form-group">
            <label class="control-label col-md-2" for="Nom"></label>
            <div class="col-md-10">
                <input class="form-control text-box single-line btn-primary" type="submit">
            </div>
        </div>

    </form>

</div>

<script type="text/javascript">

    function jsRaces() {
        var race = document.getElementById("type").selectedIndex;
        document.getElementById("race").selectedIndex = null;

        $("#race option").each(function () {
            if (this.className == race) {
                this.hidden = false;
            } else {
                this.hidden = true;
            }

        });

    }

    function changeStatut() {
        var statutCompte = document.getElementById("statutAnimal").selectedIndex;

        if (statutCompte == 1) {
            document.getElementById("statutAnimal").style.backgroundColor = "#0C0";
        } else {
            document.getElementById("statutAnimal").style.backgroundColor = "#C00";
        }
    }

</script>

AnimDispa/Views/Animaux/Index.cshtml
@model AnimDispa.Models.ViewModelAnimaux

@{
    ViewBag.Title = "Index";
}
<div class="jumbotron">
    <h1>AnimDispa</h1>
    <p class="lead">Site pour déclarer la perte de son animal de compagnie</p>

</div>

<style>
    .table-largeur {
        width: 50%;
    }

    .enteteMsg {
        width: 25%;
    }

    .listMsg {
        background-color: #FFF;
    }

    .textarea-full {
        width: 100%;
        max-width: 100%;
        min-width: 100%;
        min-height: 100px;
        max-height: 400px;
        padding: 10px;
    }

    .maxheight {
        max-height: 200px;
        height: auto;
        max-width: 100%;
        width: auto;
    }

</style>

<div class="row">
    <div class="col-sm-10 col-sm-offset-1 well">
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <td class="table-largeur">
                    <img class="img-responsive maxheight" src="~/content/img/@Html.DisplayFor(model => model.animal.PhotoPrincipale)" alt="Image de l'animal'" />
                </td>
                <td><h1>@Html.DisplayFor(model => model.animal.Nom)</h1></td>
            </tr>
            <tr>
                <td>Race</td>
                <td>@Html.DisplayFor(model => model.animal.Race.Libelle)</td>
            </tr>
            <tr>
                <td>Poids</td>
                <td>@Html.DisplayFor(model => model.animal.Poids) kg</td>
            </tr>
            <tr>
                <td>Couleur</td>
                <td>@Html.DisplayFor(model => model.animal.Couleur)</td>
            </tr>
            <tr>
                <td>Tatouage</td>
                <td>@Html.DisplayFor(model => model.animal.Tatouage)</td>
            </tr>
            <tr>
                <td>Puce</td>
                <td>@Html.DisplayFor(model => model.animal.Puce)</td>
            </tr>
            <tr>
                <td>Propriétaire</td>
                <td>@Html.DisplayFor(model => model.animal.Compte.Prenom) @Html.DisplayFor(model => model.animal.Compte.Nom)</td>
            </tr>
            <tr>
                <td>Statut</td>
                <td style="color: @Html.DisplayFor(model => model.animal.StatutAnimal.Couleur); font-weight:bold;">@Html.DisplayFor(model => model.animal.StatutAnimal.Libelle)</td>
            </tr>
        </table>

        <h4>Lieu</h4>
        <table class="table table-condensed table-striped table-bordered">
            <tr>
                <td class="table-largeur">Département</td>
                <td>@Html.DisplayFor(model => model.animal.Departement.numero) - @Html.DisplayFor(model => model.animal.Departement.Libelle)</td>
            </tr>
            <tr>
                <td>Rue</td>
                <td>@Html.DisplayFor(model => model.animal.Rue)</td>
            </tr>
            <tr>
                <td>Code postal</td>
                <td>@Html.DisplayFor(model => model.animal.CodePostal)</td>
            </tr>
            <tr>
                <td>Ville</td>
                <td>@Html.DisplayFor(model => model.animal.Ville)</td>
            </tr>
        </table>

        @if (Session["idConnecte"] != null && Model.animal.Compte.Id.ToString() == Session["idConnecte"].ToString())
        {
            @Html.ActionLink("Modifier les informations", "Edit", "Animaux", new { id = Model.animal.Id }, htmlAttributes: new { @class = "btn btn-primary pull-right" })
        }

        
        <br /><br />
        <hr />

        <div class="col-md-12">
            <div id="googleMap" style="width:100%;height:400px;"></div>

            
            @Scripts.Render("~/bundles/jquery")
            
            <script>
                var map = null;
                $.ajax({
                    method: "GET",
                    url: "https://maps.googleapis.com/maps/api/geocode/json",
                    data: {address : "@Model.animal.Ville" ,key : "AIzaSyBZi1BzZ5hzvr_BOe2Z6Dh0W2xxgOvLcx0" }
                }).done(function (msg) {
                    console.log(msg["results"][0]["geometry"]["location"]["lat"]);
                    latLong =  new google.maps.LatLng(msg["results"][0]["geometry"]["location"]["lat"],msg["results"][0]["geometry"]["location"]["lng"]);
                    //var mapProp = {
                    //    center: latLong,
                    //    zoom: 15,
                    //};
                    //var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
                    //map.setCenter(latLong);
                    var mapProp = {
                        center: latLong,
                        zoom: 15,
                    };

                    var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);

                    

                        @{
                        var i = 0;
                        foreach (var item in Model.ListeMarker)
                        {
                            i++;
                            @:var coord = new google.maps.LatLng(@item.Latitude, @item.Longitude);
                            //                            @:addMarker(new google.maps.LatLng(@item.Longitude,@item.Longitude), map);

                            @:var marker = new google.maps.Marker({
                                @:    map: map,
                                    @:    draggable: false,
                                    @:    label:@Html.Raw("'"+ i + "'"),
                            @:    animation: google.maps.Animation.DROP,
                            @:    position: coord
                            @:});
                    }
                }



                    google.maps.event.addListener(map, 'click', function (event) {
                        var myLatLng = event.latLng;
                        var lat = myLatLng.lat();
                        var lng = myLatLng.lng();
                        console.log(myLatLng);
                        //alert("lat : " + lat + " long : " + lng)

                        console.log("Avant le ajax");
                        if (confirm("Avez-vous bien vu l'animal ?")) {
                            addMarker(event.latLng, map);
                            $.ajax({
                                method: "GET",
                                url: "@Url.Action("MarkerAdd", "Ajax", new { })",
                                data: { lat: lat , idAnim: @Model.animal.Id , lgt: lng }
                            })
                            .done(function (msg) {
                                alert("Data Saved: " + msg);
                            });
                        }
                    });


                    marker.setMap(map);
                });


                function myMap() {

                }

                function addMarker(location, map) {
                    var marker = new google.maps.Marker({
                        position: location,
                        map: map
                    });
                }

                function toggleBounce() {
                    if (marker.getAnimation() !== null) {
                        marker.setAnimation(null);
                    } else {
                        marker.setAnimation(google.maps.Animation.BOUNCE);
                    }
                }
                
            </script>
            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBZi1BzZ5hzvr_BOe2Z6Dh0W2xxgOvLcx0"></script>


        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-10 col-sm-offset-1 well">

        @foreach (var item in Model.lesMessages)
        {
            <div>
                <table class="table table-bordered table-condensed listMsg">
                    <tr>
                        <td class="enteteMsg">
                            <p>@Html.DisplayFor(modelItem => item.Date)</p>
                            <p>@Html.DisplayFor(modelItem => item.Compte.Prenom) @Html.DisplayFor(modelItem => item.Compte.Nom)</p>
                            <p style="color: @Html.DisplayFor(modelItem => item.Compte.Role.Couleur)">@Html.DisplayFor(modelItem => item.Compte.Role.Libelle)</p>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Libelle)
                        </td>
                    </tr>
                </table>
            </div>

        }

        @if (Session["IdConnecte"] != null || Model.conf.Value == true)
        {
            <form method="POST" action="/Messages/Create">
                <h3>Laissez un message :</h3>
                <input type="hidden" name="id" value="@Html.DisplayFor(model => model.animal.Id)" />
                <textarea class="textarea-full" name="description" required></textarea>
                <br /><br />
                <input type="submit" class="btn btn-primary" />
            </form>
        }
    </div>
</div>